"""Initial Migration

Revision ID: 091096b73dfc
Revises: 
Create Date: 2021-09-17 17:09:49.188653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '091096b73dfc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filter_rule',
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.PickleType(), nullable=True),
    sa.Column('destination', sa.PickleType(), nullable=True),
    sa.Column('service', sa.PickleType(), nullable=True),
    sa.Column('action', sa.String(length=10), nullable=True),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.Column('mtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('name')
    )
    op.create_table('host_object',
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ipv4', sa.String(length=19), nullable=True),
    sa.Column('ipv6', sa.String(length=43), nullable=True),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.Column('mtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('nat_rule',
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('destination', sa.String(length=32), nullable=True),
    sa.Column('service', sa.String(length=32), nullable=True),
    sa.Column('target', sa.String(length=32), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=True),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.Column('mtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('network_group_object',
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('children', sa.Text(), nullable=True),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.Column('mtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('network_object',
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ipv4', sa.String(length=19), nullable=True),
    sa.Column('ipv6', sa.String(length=43), nullable=True),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.Column('mtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('service_group_object',
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('children', sa.Text(), nullable=True),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.Column('mtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('service_object',
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('protocol', sa.String(length=3), nullable=False),
    sa.Column('dport_low', sa.Integer(), nullable=False),
    sa.Column('dport_high', sa.Integer(), nullable=False),
    sa.Column('sport', sa.Integer(), nullable=True),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.Column('mtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_object')
    op.drop_table('service_group_object')
    op.drop_table('network_object')
    op.drop_table('network_group_object')
    op.drop_table('nat_rule')
    op.drop_table('host_object')
    op.drop_table('filter_rule')
    # ### end Alembic commands ###
