"""Added FirewallObject

Revision ID: a058658fcce4
Revises: 091096b73dfc
Create Date: 2021-09-22 14:32:52.291356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a058658fcce4'
down_revision = '091096b73dfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firewall_object',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('primary_address', sa.String(length=32), nullable=False),
    sa.Column('additional_addresses', sa.PickleType(), nullable=True),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.Column('mtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('primary_address')
    )
    op.create_table('policy',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('targets', sa.PickleType(), nullable=False),
    sa.Column('filter_rules', sa.PickleType(), nullable=False),
    sa.Column('nat_rules', sa.PickleType(), nullable=True),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.Column('mtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('name')
    )
    op.alter_column('filter_rule', 'action',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.create_unique_constraint(None, 'nat_rule', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nat_rule', type_='unique')
    op.alter_column('filter_rule', 'action',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_table('policy')
    op.drop_table('firewall_object')
    # ### end Alembic commands ###
